#!/usr/bin/env bash
#
# Copyright (c) 2012-2013 Karsten Heinze
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR
# ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
# CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
#

set +x

if [[ $# != 1 || ! -d $1 ]]; then
    echo "usage: $0 <dir>"
    exit 1
fi

BASE_DIR=${1%/}

for DIR in $(find "$BASE_DIR" -type d | sort); do
    # Ignore DIRs without mp3 files.
    if (( $(find $DIR -maxdepth 1 -iname "*.mp3" -type f | wc -l) == 0 )); then
        continue;
    fi

    echo -n "$DIR"

    # Fetch covers.
    covergrabber "$DIR" &> /dev/null

    # If there is a cover, apply!
    # Use single brackets for glob expansion.
    if [ -f "$DIR"/cover.* ]; then
        echo ""

        COVER=$(ls "$DIR"/cover.*)

        for FILE in "$DIR"/*.mp3; do
            echo -n "    $(basename $FILE)" 

            # Don't overwrite.
            if (( $(eyeD3 "$FILE" | grep -c "FRONT_COVER" ) > 0 )); then
                echo " [OK]"
                continue
            fi
            eyeD3 --add-image="$COVER":FRONT_COVER "$FILE" &> /dev/null
            if (( $? == 0 )); then
                echo " [OK]"
            else
                echo " [ERROR]"
            fi
        done
    else
        echo " [NO COVER FOUND]"
    fi
done
